### ISSUE TITLE
Access priviliges

### ISSUE THREAD

**Issue by jashanj0tsingh** [GIPSY-dev/WSC-Gen#2]
I can't seem to commit/push to the repository. 

`remote: Permission to GIPSY-dev/WSC-Gen.git denied to jashanj0tsingh.
fatal: unable to access 'https://github.com/GIPSY-dev/WSC-Gen.git/': The requested URL returned error: 403`

**Comment by smokhov** [comment]
Default was read apparently; please try again

**Comment by jashanj0tsingh** [comment]
Sir,

I tried to create a branch named Datasets and a few commits and push them.
However, as you can see from the attached screenshot it still failed to do
so.

**Comment by smokhov** [comment]
On Fri, 24 Mar 2017, Jashanjot Singh wrote:

> Date: Fri, 24 Mar 2017 19:16:44 -0700
> From: Jashanjot Singh <notifications@github.com>
> 
> I tried to create a branch named Datasets and a few commits and push them.
> However, as you can see from the attached screenshot it still failed to do
> so.

Your screenshot's time appears two minutes before I fixed it and reported 
in my comment earlier. Did you try again?

-- 
Serguei A. Mokhov, PhD                                   |  /~\     The ASCII
Computer Science and Software Engineering &              |  \ /  Ribbon Campaign
Concordia Institute for Information Systems Engineering  |   X     Against HTML
Concordia University, Montreal, Quebec, Canada           |  / \       Email!

**Comment by jashanj0tsingh** [comment]
Sir,

The time was coincidently different due to a different time zone in the VM
image. As you can see in this attachment as well. The Winnipeg time zone
made it exactly minus one hour. Also, I yet tried it again.

**Comment by jashanj0tsingh** [comment]
Please close this issue. It has been resolved.
