### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by smokhov** [GIPSY-dev/WSC-Gen#3]
@jashanj0tsingh -- we need to modernize a bit the README. The URL is dead, the contact should be `gipsy@encs.concordia.ca`, very basic running instructions, etc.

**Comment by smokhov** [comment]
Current content can be moved at the bottom for now under section called "Legacy README".

**Comment by jashanj0tsingh** [comment]
Content moved to the bottom as asked. Also updated the link for the same but on a web archive. A brief instruction for now.
